version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: flask_app
    environment:
      MONGO_URI: mongodb://mongo_container:27017/talle_api_rest
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

volumes:
  mongo_data: