# Usar una imagen base de Python
FROM python:3.8-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el archivo del cliente al contenedor
COPY cliente.py /app/

# Instalar las dependencias necesarias
RUN pip install --no-cache-dir requests

# Establecer las variables de entorno predeterminadas
ENV AUTH_URL=http://localhost:5000/login
ENV SALUDO_URL=http://localhost:5000/saludo

# Comando para ejecutar la aplicación cliente
CMD ["python", "cliente.py"]
